# Obtain a key here: https://platform.openai.com
openai-key: "sk-OPENAI_API_KEY"

# This is the root URL that will be used for all API requests to OpenAI.
# The URL can include a base path, but in that case, the base path should always end with a /.
openai-url: "https://api.openai.com/v1/"
openai-query-param: ""
openai-headers: ""

openai-model: "gpt-4o"

# Log conversation messages to server console, useful for catching abuse
log-conversations: true

# Either "system" or "user"; configures the type of message the "preamble"
# will be. "user" is more likely to work with GPT-3.5
preamble-message-type: system
