name: VillagerGPT
version: '${version}'
main: tj.horner.villagergpt.VillagerGPT
api-version: 1.20.5
commands:
  ttv:
    description: Start a conversation with a villager
    permission: villagergpt.ttv
  ttvclear:
    description: Clear your conversation with a villager
    permission: villagergpt.ttvclear
  ttvend:
    description: End the current villager conversation
    permission: villagergpt.ttvend
permissions:
    villagergpt.ttv:
        default: true
    villagergpt.ttvclear:
        default: true
    villagergpt.ttvend:
        default: true
